language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm test

after_success:
  - npm test -- --coverage

before_deploy:
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: info@inveniosoftware.org
    api_key:
      secure: # FILL ME
    on:
      branch: master
      tags: true
      repo: inveniosoftware/react-invenio-forms
